### ISSUE TITLE
Customize checked steps icon

### ISSUE THREAD

**Issue by kbsali** [shaozi/svelte-steps#25]
I can't seem to find a way to customize the checked steps icon.
The issue is that I would like to make the "primary" color white, and the check mark of the Check svg is white too as far as I can see. 
A possible solution could be to allow overriding the icon of checked steps?

Thanks for your help/hint.

**Comment by shaozi** [comment]
This is a reasonable request. Do you think you can create a PR?

**Comment by kbsali** [comment]
(sorry for the late answer) I'll try yes!

**Comment by shaozi** [comment]
Nice! Search for `Check` in the `lib/Steps.svelte` file. Then create a prop that will take a component, and finally use `<svelte:compoent this={check}/>` to replace the `<Check/>`

**Comment by shaozi** [comment]
re-read your first comment, actually for your case, you can set the `light` prop to change the color of the icon:

```svelte
<Steps {steps} primary="white" light="black"/>
```

REPL here: https://svelte.dev/repl/1d80b51acef342d5bc1420d70958b275?version=3.48.0

**Comment by kbsali** [comment]
Oh Wow! It indeed does exactly what I was looking for :)
(the param naming is a bit strange though :sweat_smile: )

Thanks a lot! I still might try to issue a PR in case you'd want to change the icon :)

**Comment by kbsali** [comment]
:ok_hand:
