### ISSUE TITLE
Is there a way to customize the icon for completed steps?

### ISSUE THREAD

**Issue by gorgsenegger** [shaozi/svelte-steps#29]
Hi shaozi,

I'd like to customize the icon for completed (i.e. previous) steps and can't find a way to do this. Right now it looks like this:

![image](https://user-images.githubusercontent.com/22298273/194728344-024e70c5-4fb2-416b-ba79-f6e3150850ec.png)

when - as shown above - I'm currently on "Step 4" of my five steps. Step 5 shows an exclamation mark which I pass in like this:

    <Steps
        {steps}
        current={currentStep}
        clickable={true}
        primary="#9e3aa3"
        secondary="#ee8af3"
        on:click={handleClick}
    />

Where my steps initially look like this:

        { text: "Step 1", step: 1, icon: Exclamation },
        { text: "Step 2", step: 2, icon: Exclamation },
        { text: "Step 3", step: 3, icon: Exclamation },
        { text: "Step 4", step: 4, icon: Exclamation },
        { text: "Step 5", step: 5, icon: Exclamation }

As my step icons are `clickable` I'd like the user to be able to jump between different steps even if the required configuration for a particular step is still incomplete/invalid. To indicate this I pass the `Exclamation` icon component (and set it for each step correspondingly, based on a variable for each of the available steps - if the step configuration is complete it don't use that icon but the standard tick mark).

As shown in my image it works for steps that are next (here: Step 5), but not for previous steps (here: Step 2, which should be shown with an exclamation mark (which is also set as an icon but not showing)). So for completed/previous steps it seems that the icon (if one is passed) is overridden with the standard tick mark icon.

Hope this wasn't too complicated to explain ;-)

**Comment by gorgsenegger** [comment]
After looking through with a bit more time I can see that my assumption is true for overriding the icon for previous steps:

	{#if step.icon}
	    {#if i < $progress}
		    <Check />
		{:else if step.iconProps}
		    <svelte:component this={step.icon} {...step.iconProps} />
		{:else}
			<svelte:component this={step.icon} />
		{/if}
	{:else if i < $progress}
		<Check />
	{:else}
		<span class="steps__number">{i + 1}</span>
	{/if}

**Comment by shaozi** [comment]
You are right. 

I can add one more option into the `steps` property, such as this:

```
 { text: "Step 1", step: 1, icon: Exclamation, successIcon: Check }
```

Thoughts?

**Comment by gorgsenegger** [comment]
Thanks for getting back to me. I think within the first branch of the `if` statement there'd have to be some further checks to be performed.

Maybe instead of

    ...
    {#if i < $progress}
	    <Check />
	{:else if step.iconProps}
    ...

something like this?

    ...
    {#if i < $progress}
        {#if step.successIcon}
            <svelte:component this={step.icon} {...step.iconProps} /> 
        {:else}
            <Check />
        {/if}
    {:else if step.iconProps}
    ...

**Comment by shaozi** [comment]
Do you mind create a PR for this?

**Comment by gorgsenegger** [comment]
Yes, that sounds like the way to go - differentiate the three possible states as suggested so that all possibilities are covered.

**Comment by gorgsenegger** [comment]
Yes, that sounds like the way to go - differentiate the three possible states as suggested so that all possibilities are covered.

Sorry for the late reply, I didn't hit the "Comment" button a couple of days ago so this wasn't posted :-/

**Comment by shaozi** [comment]
I have pushed a new version 2.4.0 that address this request. now you can specify an `alert: true` field in the step object to indicate this step need attention.

and in the `<Steps>` you can specify `checkIcon`, `alertIcon`, and `alertColor` to customize the icon and color.

- `checkIcon`: User defined check icon for passed steps. If not specified, use the default check mark. Set to `null` if you don't want a check icon.
- `alertIcon`: User defined alert icon for passed steps that has truthful `alert` property. If not specified, use the default alert icon. Set to `null` if you don't want an alert icon.
- `alertColor`: User defined bg color for passed steps that has truthful `alert` property. Default 'var(--bs-danger, #dc3545)'

**Comment by gorgsenegger** [comment]
Hi @shaozi,

Thank you for following up on this and providing a new version. I'll definitely look into it within the next couple of days and let you know what I think - I'd also close this issue.

Great to have this component, I'm using it in a project I've been working on for a couple of months now.

**Comment by gorgsenegger** [comment]
Sorry for the delay,  I meant to do this over the holidays and then forgot :-/

Works great and I'll close the issue. Thanks again!
